services:
  workspace:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    volumes:
      - .:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
